# Generated by Django 2.2.5 on 2022-04-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('b_no', models.AutoField(primary_key=True, serialize=False)),
                ('b_date', models.DateTimeField(auto_now_add=True)),
                ('b_contents', models.TextField()),
                ('b_title', models.CharField(max_length=100)),
                ('view', models.IntegerField(default=0)),
                ('writer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('i_no', models.AutoField(primary_key=True, serialize=False)),
                ('image_contents', models.TextField()),
                ('image_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pile',
            fields=[
                ('p_no', models.AutoField(primary_key=True, serialize=False)),
                ('p_content', models.TextField()),
                ('p_date', models.DateTimeField(auto_now_add=True)),
                ('writer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('r_no', models.AutoField(primary_key=True, serialize=False)),
                ('r_date', models.DateTimeField(auto_now_add=True)),
                ('r_contents', models.TextField()),
                ('writer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
    ]
