# Generated by Django 4.0.4 on 2022-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('f_no', models.AutoField(primary_key=True, serialize=False)),
                ('f_title', models.CharField(max_length=200)),
                ('uploadedFile', models.FileField(upload_to='Uploaded Files/')),
                ('f_date', models.DateTimeField(auto_now=True)),
                ('f_writer', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Pile',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Pile',
        ),
    ]
