# Generated by Django 4.0.4 on 2022-05-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_file_delete_pile'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='File',
        ),
    ]
